/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as DataIngestionRouteImport } from './routes/data-ingestion'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegionalRouteImport } from './routes/regional'
import { Route as AgencyCodeRouteImport } from './routes/agency.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIngestionRoute = DataIngestionRouteImport.update({
  id: '/data-ingestion',
  path: '/data-ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalRoute = RegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyCodeRoute = AgencyCodeRouteImport.update({
  id: '/agency/$code',
  path: '/agency/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/countries': typeof CountriesRoute
  '/data-ingestion': typeof DataIngestionRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/regional': typeof RegionalRoute
  '/agency/$code': typeof AgencyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/countries': typeof CountriesRoute
  '/data-ingestion': typeof DataIngestionRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/regional': typeof RegionalRoute
  '/agency/$code': typeof AgencyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/countries': typeof CountriesRoute
  '/data-ingestion': typeof DataIngestionRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/regional': typeof RegionalRoute
  '/agency/$code': typeof AgencyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/countries'
    | '/data-ingestion'
    | '/feedback'
    | '/login'
    | '/regional'
    | '/agency/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/countries'
    | '/data-ingestion'
    | '/feedback'
    | '/login'
    | '/regional'
    | '/agency/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/countries'
    | '/data-ingestion'
    | '/feedback'
    | '/login'
    | '/regional'
    | '/agency/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CountriesRoute: typeof CountriesRoute
  DataIngestionRoute: typeof DataIngestionRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  RegionalRoute: typeof RegionalRoute
  AgencyCodeRoute: typeof AgencyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-ingestion': {
      id: '/data-ingestion'
      path: '/data-ingestion'
      fullPath: '/data-ingestion'
      preLoaderRoute: typeof DataIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional': {
      id: '/regional'
      path: '/regional'
      fullPath: '/regional'
      preLoaderRoute: typeof RegionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/$code': {
      id: '/agency/$code'
      path: '/agency/$code'
      fullPath: '/agency/$code'
      preLoaderRoute: typeof AgencyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CountriesRoute: CountriesRoute,
  DataIngestionRoute: DataIngestionRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  RegionalRoute: RegionalRoute,
  AgencyCodeRoute: AgencyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
